name 'vmworld'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures vmworld'
long_description 'Installs/Configures vmworld'
version '0.1.0'
